### ISSUE TITLE
这个支持theme-hao这个主题吗

### ISSUE THREAD

**Issue by Xiaotingwen** [ichenhe/halo-twikoo#2]
我在环境中装了这个插件，并关闭了[评论组件]，但是文章下面没有出现twikoo的评论窗口

**Comment by ichenhe** [comment]
测试了下的确有这个问题，看到 Hao 主题内置了 Twikoo 的支持，可能也因此没有完全兼容 Halo 原生的插件化评论系统。我测试了同一开发者的其他主题，都没有问题。

建议联系 Hao 主题开发者。

**Comment by ichenhe** [comment]
Hao 主题开发者建议使用主题内置的第三方评论。
